### ISSUE TITLE
Large process cannot be documented in web app

### ISSUE THREAD

**Issue by JustAGirlyGeek** [shunkosa/sfdx-flowdoc-plugin#17] opened 2020-08-10 17:00 UTC
I tried running the herokuapp for multiple orgs on two different browsers but none of the processes get documented. I get the following blank screen and have let it sit for a few hours with no results: 

![image](https://user-images.githubusercontent.com/4005665/89809266-51b18b00-db09-11ea-951c-0af5bdf5145f.png)

**Comment by shunkosa** [comment] 2020-08-11 08:38
@JustAGirlyGeek Thank you for reporting! I'm afraid I cannot reproduce it in my dev orgs. Did you remember the approx. date/time you tried? I'll look into the heroku logs.

**Comment by JustAGirlyGeek** [comment] 2020-08-11 11:13
Hi Shun,

I tried at approximately the time I posted the issue. I can try again in one of my sandboxes later and let you know.

Thanks,
Maria

**Comment by shunkosa** [comment] 2020-08-11 12:43
Sure! I found there's some timeout error around the time you tried. I believe this will be resolved by retrying. Could you please check the browser console too, just in case?

**Comment by JustAGirlyGeek** [comment] 2020-08-11 13:06
Hi Shun,

This is what appears in the chrome console:

[image: image.png]

**Comment by shunkosa** [comment] 2020-08-12 08:11
Hello Maria,
Your attachment seems not uploaded well😢 BTW, There's another report about the blank screen. I just update the web app to avoid time-out error. Try to clear browser cache and see whether it works or not🙏

**Comment by JustAGirlyGeek** [comment] 2020-08-12 13:02
YAY!!! That worked! Thank you so much!

**Comment by JustAGirlyGeek** [comment] 2020-08-12 13:04
However, I tried exporting a few of them that I need and get this error in
developer tools:

Failed to load resource: the server responded with a status of 413 (Payload
Too Large)

**Comment by shunkosa** [comment] 2020-08-13 03:49
We're making progress :) 
Is the above error happens when you press the download button for a specific flow? or Load more link?

**Comment by JustAGirlyGeek** [comment] 2020-08-13 11:05
The error occurs when I try to download specific flows. It works for some and not others.

**Comment by shunkosa** [comment] 2020-08-13 12:15
Thanks again. I need to fix the document generation process on the server-side and it will be a large fix work. The current workaround is using the CLI plugin instead of the web app. Sorry for the inconvenience but I'll let you know the progress here soon.

**Comment by shunkosa** [comment] 2020-08-13 15:11
@JustAGirlyGeek Ah, I missed the default file size limit setting on node.js, and probably the reason of this issue is that the file size of the documentation is greater than the default limit. I just updated it so please try again at your convenience!

**Comment by JustAGirlyGeek** [comment] 2020-08-13 15:28
Hi Shun, same error unfortunately:

Failed to load resource: the server responded with a status of 413 (Payload
Too Large)

**Comment by shunkosa** [comment] 2020-08-14 02:37
Seems working right now. Thanks again @JustAGirlyGeek

**Closed by shunkosa** 2020-08-14 02:37 UTC
Labels: needs investigation, performance issue
